### ISSUE TITLE
Update instructions environment setup on Windows

### ISSUE THREAD

**Issue by lmejn** [ACRF-Image-X-Institute/packaging_demo#22]
I would like to update the Windows section of [Environment set up](https://acrf-image-x-institute.github.io/packaging_demo/set_up_environment.html#windows). It seems Windows can be a bit tricky/non-intuitive regarding the availability of Python in the command line or PowerShell, especially since some installation methods don't automatically add the interpreter to PATH. I would like to add a small section on how to access `python.exe`, if it's not available.

**Comment by bwheelz36** [comment]
you should probably update the bottom of this page, looks like I never actually wrote the powershell part...
https://acrf-image-x-institute.github.io/packaging_demo/set_up_environment.html
