### ISSUE TITLE
Adding a pylint badge

### ISSUE THREAD

**Issue by lmejn** [ACRF-Image-X-Institute/packaging_demo#37]
I think it would be good to add a pylint badge to the repository. This way we can show people that pylint is used and that they should use it when working on the code.

Looks like there is some documentation on how to implement [here](https://pylint.readthedocs.io/en/latest/user_guide/installation/badge.html)

The code for the badge would be added to the README.md, and would look something like this:
```
[![linting: pylint](https://img.shields.io/badge/linting-pylint-yellowgreen)](https://github.com/PyCQA/pylint)
```

**Comment by ayushmaanshrotriya** [comment]
will do. you can assign me

**Comment by bwheelz36** [comment]
Thanks @ayushmaanshrotriya, but actually we just use this repository for education purposes. Appreciate the offer though!

**Comment by ayushmaanshrotriya** [comment]
no problem
